---
- name: "Create group {{ vector_group }}"
  become: true
  ansible.legacy.group:
    name: "{{ vector_group }}"
    state: present

- name: "Add user {{ vector_user }}"
  become: true
  ansible.builtin.user:
    name: "{{ vector_user }}"
    group: "{{ vector_group }}"

- name: Make sure Vector directory exists
  become: true
  ansible.legacy.file:
    path: /etc/vector
    state: directory
    owner: "{{ vector_user }}"
    group: "{{ vector_group }}"

- name: Make sure var Vector directory exists
  become: true
  ansible.legacy.file:
    path: /var/lib/vector/
    state: directory
    owner: "{{ vector_user }}"
    group: "{{ vector_group }}"

- name: Unarchive Vector
  ansible.builtin.unarchive:
    src: https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-x86_64-unknown-linux-musl.tar.gz
    dest: /tmp
    remote_src: true

- name: Copy vector to etc
  become: true
  ansible.builtin.copy:
    src: /tmp/vector-x86_64-unknown-linux-musl/bin/vector
    dest: /usr/bin/vector
    owner: "{{ vector_user }}"
    group: "{{ vector_group }}"
    mode: '0755'
    remote_src: true
  notify: Restart and enable Vector service

- name: Copy vector.service file
  become: true
  ansible.builtin.copy:
    src: /tmp/vector-x86_64-unknown-linux-musl/etc/systemd/vector.service
    dest: /etc/systemd/system/vector.service
    owner: root
    group: root
    mode: '0755'
    remote_src: true
  notify: Restart and enable Vector service

- name: Add vector.yaml file
  become: true
  ansible.builtin.template:
    src: templates/vector.yaml.j2
    dest: /etc/vector/vector.yaml
    mode: '0755'
  notify: Restart and enable Vector service
