---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  # - name: ubuntu
  #   image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2404}-ansible:latest"
  #   command: ${MOLECULE_DOCKER_COMMAND:-""}
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:rw
  #   pre_build_image: true
  #   privileged: true
  #   cgroupns_mode: host
  - name: centos
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos8}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-"/usr/sbin/init"}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    pre_build_image: true
    privileged: true
    cgroupns_mode: host
    override_command: false
provisioner:
  name: ansible
verifier:
  name: ansible
